### ISSUE TITLE
jnlp_secret resource should probably be marked sensitive

### ISSUE THREAD

**Issue by robbert229** [aidanleuck/terraform-provider-jenkins#3]
The `jnlp_secret` field on the node data source should probably be marked sensitive to prevent accidentally leaking the jnlp secret
https://github.com/aidanleuck/terraform-provider-jenkins/blob/dbce392c783659193f78a7ef030baa88ab925dd5/internal/provider/node_data_source.go#L98

**Comment by aidanleuck** [comment]
Will release a patch for this tonight.

**Comment by aidanleuck** [comment]
Fixed in PR #4
